services:
  # 1. Service Database (Yang sudah Anda punya)
  mysqldb:
    image: mysql:8.0
    container_name: sejukin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sejukin_db
    ports:
      - "3307:3306" # Port luar 3307, port dalam 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sejukin-net

  # 2. Service Aplikasi Backend (BARU)
  backend:
    build: .  # Build dari Dockerfile di folder ini
    container_name: sejukin-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysqldb
    networks:
      - sejukin-net

volumes:
  mysql_data:

networks:
  sejukin-net:
    driver: bridge